### ISSUE TITLE
lc store_false

### ISSUE THREAD

**Issue by paulin-mipt** [alexvi88/text_generator#11]
https://github.com/alexvi88/text_generator/blob/c7ecc2557a19a303980370813bd355ae5211f05b/train.py#L17

Посмотрите в argparse на `action='store_false'`, так будет лучше. И, кстати, равенство на None проверяется `is None` / `is not None`

**Comment by alexvi88** [comment]
Добрый день. Исправил. А чем принципиально отличается myObj != None и myObj is not None?

**Comment by paulin-mipt** [comment]
Кажется, только тем, что так принято писать. Это касается именно сравнений с None, больше ничего

**Comment by paulin-mipt** [comment]
Засчитываю ревью, кстати

**Comment by alexvi88** [comment]
Отлично. Большое спасибо за замечания.
