### ISSUE TITLE
дублирование кода

### ISSUE THREAD

**Issue by paulin-mipt** [alexvi88/text_generator#5]
generate_model_from_stdin и generate_model_from_file подозрительно похожи. Давайте склеим их в одну функцию?

**Comment by alexvi88** [comment]
Но ведь дублирования кода нет. Они похожи, но если их объединить в один метод, то ничего кроме просто вставки кода одного метода в другой не получится.

**Comment by paulin-mipt** [comment]
Они почти абсолютно одинаковы, если учесть, что чтение "до пустой строки" из консоли -- это неправильно, а лучше читать точно так же: for line in sys.stdin.readlines()

В таком случае эквивалент "end of file" -- шорткат ctrl+d, который завершает ввод

**Comment by alexvi88** [comment]
Извиняюсь, перепутал generate_model_from_stdin и generate_model_from_directory. Действительно есть дублирование кода. Исправил.
